### ISSUE TITLE
Can't get write token to my own repo

### ISSUE THREAD

**Issue by lalyos** [CenturyLinkLabs/docker-reg-client#2]
First of all thanks for creating this library.

I'm trying to create a tag for my image. For that i need a token. I do something like:
https://github.com/lalyos/register/blob/master/main.go#L39-L42

But i'm getting a  403 error translated as: `Access denied, you don't have access to this repo`.
The user/password is correct, as i get a correct token for `GetReadTokenWithAuth()`.
## API

By the [api docs](https://docs.docker.com/reference/api/docker-io_api/#authorize-a-token-for-a-user-repository) the url for getting a token should be:

```
PUT /v1/repositories/(namespace)/(repo_name)/auth
```

but seems like the implementation is missing the `/auth` postfix, see: https://github.com/CenturyLinkLabs/docker-reg-client/blob/master/registry/hub.go#L39

I've tried to add the missing '/auth' but the same error is responded ...
## Example traffic

Here is the sample network traffic:

```
[REQ] ===>  PUT /v1/repositories/sequenceiq/cloudbreak/ HTTP/1.1
Host: index.docker.io
User-Agent: Go 1.1 package http
Content-Length: 3
Authorization: Basic ZGVhcl9oYWNrZXI6aWtub3diYXNlNjRpc3Vuc2FmZTsp
X-Docker-Token: true
Accept-Encoding: gzip

[RESP] ===>  HTTP/1.1 403 FORBIDDEN
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json
Date: Thu, 09 Apr 2015 09:20:30 GMT
Server: nginx/1.6.2
Set-Cookie: csrftoken=53wN5L9B8xx4dfX6RZqe6QIWcp9WQRzv; expires=Thu, 07-Apr-2016 09:20:30 GMT; httponly; Max-Age=31449600; Path=/; secure
Set-Cookie: sessionid=lmo7ovbxqquj2zlo1w7kevyjgurw0bgq; expires=Sun, 12-Apr-2015 20:40:30 GMT; httponly; Max-Age=300000; Path=/; secure
Strict-Transport-Security: max-age=31536000
Vary: Cookie
X-Frame-Options: SAMEORIGIN
```

**Comment by bdehamer** [comment]
@lalyos 

You mentioned that you are using `GetReadTokenWithAuth()` but I believe that you actually need a write-token in order to set a tag on an image. Can you try again with `GetWriteToken()` instead.

Here's a quick test I just ran that seemed to work for me

```
package main

import (
    "github.com/CenturyLinkLabs/docker-reg-client/registry"
)

func main() {
    c := registry.NewClient()
    ba := registry.BasicAuth{"bdehamer", "password"}
    auth, _ := c.Hub.GetWriteToken("bdehamer/foo", ba)
    c.Repository.SetTag("bdehamer/foo", "88ce120281e2d990939d4d6630a4e5ca8804bda87cade6c026663bbcd09f519b", "newtag", auth)
}
```

**Comment by lalyos** [comment]
Hi Brian,

What i tried to say, if you check the code:
https://github.com/lalyos/register/blob/master/main.go#L39-L42

I am using `GetReadTokenWithAuth()` just to validate that the user/password combination is correct.
Otherwise i do use `GetWriteToken()` and thats the point when i get a 403 error

**Comment by lalyos** [comment]
You can reproduce the error by replacing xxxxx with your real password:

```
curl -LO https://raw.githubusercontent.com/lalyos/register/master/main.go
DOCKER_HUB_USER=bdehamer DOCKER_HUB_PASSWORD=xxxxx go run main.go
```

**Comment by bdehamer** [comment]
I'm having trouble repro'ing the issue - here's what the traffic looks like from the `GetWriteToken()` call in my sample above:

```
PUT /v1/repositories/bdehamer/foo/ HTTP/1.1
Host: index.docker.io
User-Agent: Go 1.1 package http
Content-Length: 3
Authorization: Basic bm90YXNkdW1iOmFzaWxvb2s=
X-Docker-Token: true
Accept-Encoding: gzip

HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Thu, 09 Apr 2015 17:07:38 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Vary: Cookie
X-Docker-Endpoints: cdn-registry-1.docker.io
X-Frame-Options: SAMEORIGIN
X-Docker-Token: signature=e5d7e305c60a32b1fd2189ae294316618fda39ef,repository="bdehamer/foo",access=write
Set-Cookie: csrftoken=t0SVASAQ6CaJW8lWezXoSBSkjbAT7tGJ; expires=Thu, 07-Apr-2016 17:07:38 GMT; httponly; Max-Age=31449600; Path=/; secure
Set-Cookie: sessionid=9f5s63yj5tvvxqnbtfmrflimyqimpace; expires=Mon, 13-Apr-2015 04:27:38 GMT; httponly; Max-Age=300000; Path=/; secure
Strict-Transport-Security: max-age=31536000
```

**Comment by bdehamer** [comment]
The other thing I should mention is that using `GetReadTokenWithAuth()` doesn't really validate that your user/password is correct for write-access to the repo. If the repo you're trying to retrieve the token for is public (which it looks like your `sequenceiq/cloudbreak` repo is) I believe that the token is returned successfully whether or not you're using an account which has permission on that repo. 

The credentials you're using may be valid credentials, but they aren't necessarily valid for accessing that particular repo.

For example, I just used my credentials to retrieve a read-token for your `sequenceiq/cloudbreak` repo. I can't, however, use my creds to get a write-token for your repo.

**Comment by lalyos** [comment]
sure `GetReadTokenWithAuth()` doesn't give me write access. What i validate with it, that the password is correct for the given username (otherwise i would get en err).

So if you check my test: https://gist.github.com/lalyos/be8a7d3a24fc7f9e2b1a
- im able to get a read token (so i'm using a correct password)
- but i'm not able to get a write token with the same user/password combination.

When this doesn't gives you an error:

```
curl -LO https://gist.githubusercontent.com/lalyos/be8a7d3a24fc7f9e2b1a/raw/main.go
DOCKER_HUB_REPO=bdehamer/foo DOCKER_HUB_USER=bdehamer DOCKER_HUB_PASSWORD=xxxxx go run main.go
```

than it means that the **docker-reg-clien** code is correct, and Hub Repo `sequenceiq/cloudbreak` doesn't belongs to the `sequenceiq` user?!

**Comment by bdehamer** [comment]
Here's what I get

```
$ DOCKER_HUB_REPO=bdehamer/foo DOCKER_HUB_USER=bdehamer DOCKER_HUB_PASSWORD=mypassword go run main.go
readToken &{registry-1.docker.io signature=3a56610fc048067a6825be46727a270411149adc,repository="bdehamer/foo",access=read 1}
writeToken &{cdn-registry-1.docker.io signature=f0acfe7dca1e76d763000fa5cc3670f8da943d3a,repository="bdehamer/foo",access=write 2}

$ DOCKER_HUB_REPO=sequenceiq/cloudbreak DOCKER_HUB_USER=bdehamer DOCKER_HUB_PASSWORD=mypassword go run main.go
readToken &{registry-1.docker.io signature=cd7e4c116da586a9a909bba1fc21ea6320d5a375,repository="sequenceiq/cloudbreak",access=read 1}
panic: PUT https://index.docker.io/v1/repositories/sequenceiq/cloudbreak/ returned 403

goroutine 1 [running]:
main.main()
    /Users/bdehamer/dev/go-paths/gocode-docker-reg/src/main.go:37 +0x4d9

goroutine 14 [runnable]:
net/http.(*persistConn).readLoop(0xc2081f3550)
    /usr/local/Cellar/go/1.4.1/libexec/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.4.1/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 15 [select]:
net/http.(*persistConn).writeLoop(0xc2081f3550)
    /usr/local/Cellar/go/1.4.1/libexec/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.4.1/libexec/src/net/http/transport.go:661 +0xcbc
exit status 2
```

So my creds can get both read and write tokens for my repo, but my creds can only get a read token for _your_ repo.

**Comment by lalyos** [comment]
ohhh I got it! the `GetWriteToken()` works for for **normal** repos, but fails for any **automated build**.

So looks like right now I can't create a tag for automated builds...
